services:
  postgres:
    image: postgres:latest
    container_name: postgres-local

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: social_service_ea
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis-local
    ports:
      - '6379:6379'

  nats:
    image: nats:latest
    container_name: nats-local
    ports:
      - '4222:4222'

  localstack:
    image: localstack/localstack:latest
    ports:
      - '4566:4566'
    environment:
      - SERVICES=sns,s3
    volumes:
      - ./localstack:/etc/localstack/init/ready.d

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      UWS_SERVER_PORT: '3000'
      API_HTTP_SERVER_PORT: '3001'
      RPC_SERVER_PORT: '8085'
      PG_COMPONENT_PSQL_CONNECTION_STRING: 'postgresql://postgres:postgres@postgres:5432/social_service_ea'
      REDIS_HOST: 'redis'
      NATS_URL: 'nats://nats:4222'
      ARCHIPELAGO_STATS_URL: 'https://archipelago-ea-stats.decentraland.zone'
      CATALYST_URL: 'https://peer.decentraland.zone'
      PEER_SYNC_INTERVAL_MS: '45000'
      PEERS_SYNC_CACHE_TTL_MS: '90000'
      COMMS_GATEKEEPER_URL: 'https://comms-gatekeeper.decentraland.zone'
      COMMS_GATEKEEPER_AUTH_TOKEN: 'aToken'
      AWS_SNS_ARN: 'arn:aws:sns:us-east-1:000000000000:events'
      AWS_SNS_ENDPOINT: 'http://localstack:4566'
      AWS_S3_BUCKET: 'social-service-ea'
      AWS_S3_BUCKET_ENDPOINT: 'http://localstack:4566'
      AWS_REGION: 'us-east-1'
      AWS_S3_BUCKET_PREFIX: 'social'
      LOG_LEVEL: 'ALL'
      CDN_URL: 'http://localhost:4566/social-service-ea'
    ports:
      - '3000:3000'
      - '3001:3001'
      - '8085:8085'
    depends_on:
      - postgres
      - redis
      - nats
      - localstack
volumes:
  postgres-data:
