services:
  postgres:
    image: postgres:latest
    container_name: postgres-local
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: social_service_ea
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis-local
    ports:
      - '6379:6379'

  app:
    image: social-service-ea:local
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PG_COMPONENT_PSQL_CONNECTION_STRING: 'postgresql://postgres:postgres@postgres:5432/social_service_ea'
      REDIS_HOST: 'redis'
    ports:
      - '3000:3000'
      - '8085:8085'
    depends_on:
      - postgres
      - redis

volumes:
  postgres-data:
