services:
  postgres:
    image: postgres:latest
    container_name: postgres-local
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: social_service_ea
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis-local
    ports:
      - '6379:6379'

  nats:
    image: nats:latest
    container_name: nats-local
    ports:
      - '4222:4222'

  localstack:
    image: localstack/localstack:latest
    ports:
      - '4566:4566'
    environment:
      - SERVICES=sns
    volumes:
      - ./localstack:/etc/localstack/init/ready.d

  app:
    image: social-service-ea:local
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PG_COMPONENT_PSQL_CONNECTION_STRING: 'postgresql://postgres:postgres@postgres:5432/social_service_ea'
      REDIS_HOST: 'redis'
      NATS_URL: 'nats://nats:4222'
      ARCHIPELAGO_STATS_URL: 'http://archipelago-ea-stats.decentraland.zone'
      CATALYST_URL: 'https://peer.decentraland.zone'
      PEER_SYNC_INTERVAL_MS: '45000'
      PEERS_SYNC_CACHE_TTL_MS: '90000'
      AWS_SNS_ARN: 'arn:aws:sns:us-east-1:000000000000:events'
      AWS_SNS_ENDPOINT: 'http://localstack:4566'
    ports:
      - '3000:3000'
      - '8085:8085'
    depends_on:
      - postgres
      - redis
      - nats
volumes:
  postgres-data:
