name: CI/CD on main branch

on:
  push:
    branches:
      - 'main'

jobs:
  social-service-ea-deployment:
    uses: decentraland/platform-actions/.github/workflows/apps-docker-next.yml@main
    with:
      service-name: social-service-ea
      image-name: social-service-ea
      deployment-environment: dev
    secrets: inherit
