on:
  pull_request:
    paths:
      - 'docs/**'
  push:
    branches:
      - main
    paths:
      - 'docs/**'

jobs:
  build-and-deploy:
    uses: decentraland/platform-actions/.github/workflows/apps-docs.yml@main
    with:
      api-spec-file: 'docs/openapi.yaml'
      api-spec-name: 'social-service-api'
      output-bundle-file: 'docs/api-reference.yaml'
    secrets: inherit
